[package]
name = "window"
version = "0.1.0"
publish = false

[dependencies]
bevy = { version = "0.10" }

# keep the following in sync with Bevy's dependencies
winit = { version = "0.28", default-features = false }
image = { version = "0.24", default-features = false }
